dbus: check whether the client wanted interactive authentication
USBGuard/usbguard pull request #546
Opened 2022-04-15 08:06 UTC by muelli

Some clients do not want to prompt for passwords, e.g. when authorising keyboards
when the screen is locked, prompting for a password doesn't make sense because
the user cannot enter anything.
This change extracts the flags and checks whether the client called with
G_DBUS_CALL_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION.

2022-04-15 08:07 UTC, muelli commented
I'm coming from https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/676 and I haven't been able to test this, yet. Sorry.

2022-04-15 08:13 UTC, muelli commented
@hartwork may have an opinion here, too :)

2022-04-15 09:36 UTC, hartwork requested changes
Hi @muelli,

that's a nice idea, thanks for bringing this to my attention and for taking it upstream! :+1:
Some notes:

- Flag `G_DBUS_MESSAGE_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION` seems to require glib >=2.46 according to https://libsoup.org/gio/GDBusMessage.html.
  `configure.ac` does not require a specific version of glib as of today and glib <2.46 may (or may not) be used on some to-be-supported environments.
  So we either need pre-processor if-else for glib <2.46 and >=2.46 or we need to make glib >=2.46 a known and checked-for build time dependency in `configure.ac`.
  @radosroka any thoughts on these options?
  
- CI does not like the current code formatting, see:
  - log at https://github.com/USBGuard/usbguard/runs/6035863630?check_suite_focus=true#step:7:139
  - helper `./scripts/reformat-sources.sh`

- (My picky vote for `GDBusMessage* const message` adding `const`.)

- (Pull request pull request #545 probably already "fixed" the situation for gnome-settings-daemon (but this change still seems like a good idea).)

What do you think?

Best, Sebastian

2022-04-15 09:47 UTC, muelli commented
> * Flag `G_DBUS_MESSAGE_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION` seems to require glib >=2.46 according to https://libsoup.org/gio/GDBusMessage.html.
>       `configure.ac` does not require a specific version of glib as of today and glib <2.46 may (or may not) be used on some to-be-supported environments.
>       So we either need pre-processor if-else for glib <2.46 and >=2.46 or we need to make glib >=2.46 a known and checked-for build time dependency in `configure.ac`.
>       @radosroka any thoughts on these options?

good catch.
I'd bump the dependency...

2022-04-15 09:51 UTC, hartwork commented
> good catch. I'd bump the dependency...

@muelli alright, let's start with that approach then, I guess

2022-04-15 09:52 UTC, muelli commented
> * (Pull request pull request #545 probably already "fixed" the situation for gnome-settings-daemon (but this change still seems like a good idea).)

that indeed addresses part of the problem. The other part is that we try to authorise keyboards when the screen is locked. We may or may not be able to do that currently. With this change we can detect whether the user is actually allowed to authorise the device. It would still be better if the user could actually perform the authorisation, but this change probably encodes the right behaviour, because it checks whether the caller is fine with asking for authorisation.

2022-04-15 09:54 UTC, hartwork commented
We should should check with say d-feet if interactive auth still works with this patch in practice before merging, to be sure. I haven't done that, yet.

2022-04-15 10:17 UTC, hartwork requested changes
@muelli I believe this is the place to insert >=2.46 (for gio): https://github.com/USBGuard/usbguard/blob/4982b018cdda52c539e8b08ae158e54cb3a13e2f/configure.ac#L470

2022-04-15 16:31 UTC, benzea commented
Note that while this patch is correct, it causes a timeout error from the client (https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/676#note_1430710). The problem is that in various places there is code like:

```
      if (! isAuthorizedByPolkit(invocation)) {
        return;
      }
```

Which is obviously wrong, as it means that no error is returned. Instead, the code should read

```
      if (! isAuthorizedByPolkit(invocation)) {
        g_dbus_method_invocation_return_error(invocation, G_DBUS_ERROR,
          G_DBUS_ERROR_ACCESS_DENIED, "Could not authenticate request"););
        return;
      }
```

Though, not sure if `G_DBUS_ERROR_ACCESS_DENIED ` or `G_DBUS_ERROR_AUTH_FAILED ` is right. I suppose access denied, unless we pass out information about errors to talk to policykit and then return AUTH_FAILED in that case?

2022-04-16 07:33 UTC, muelli commented
> Which is obviously wrong, as it means that no error is returned. Instead, the code needs to call

uh.
thanks for pointing it out.
I know only little about dbus architecture and I am a bit surprised. I expected that kind of error to be produced by the broker, somehow.

But it feels like it would be easy to add.

reg. the type of error: The docs have this to say:
```
G_DBUS_ERROR_ACCESS_DENIED | Security restrictions don't allow doing what you're trying to do.
G_DBUS_ERROR_AUTH_FAILED | Authentication didn't work.
```
(from https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gio/gio-GDBusError.html - why does it show up under the gstreamer namespace? Rather than a more generic "dbus" namespace or something.)

2022-04-16 11:04 UTC, hartwork commented
@benzea thanks for your input, that's definitely helpful! :+1: 

@muelli how should we proceed with this pull request? Should I (a) cherry-pick your commit and make a new pull request applying the ideas of @benzea or (b) make commits for those, export using `git format-patch` and attach those files here for you to add here using `git am` or (c) … — what do you think? I should note that I have no more permissions than you in USBGuard.

2022-04-16 11:06 UTC, benzea commented
> I know only little about dbus architecture and I am a bit surprised. I expected that kind of error to be produced by the broker, somehow.

The broker isn't doing the access control, so it can't react anymore.

2022-04-16 11:10 UTC, hartwork commented
> > I know only little about dbus architecture and I am a bit surprised. I expected that kind of error to be produced by the broker, somehow.
> 
> The broker isn't doing the access control, so it can't react anymore.

Who is the broker in this picture?

2022-05-06 14:50 UTC, benzea commented
> Who is the broker in this picture?

The server that forwards messages between clients. i.e. dbus-daemon or dbus-broker in almost all cases.

2022-05-26 17:10 UTC, hartwork commented
Regarding the missing reply aspect brought up by @benzea, there is pull request #548 ready fro review and testing now.

Regarding the allow-interactive-flag aspect brought up by @muelli:
Maybe it's okay that the `dbus-send` CLI never sends the flag with its calls (so that making calls with e.g. `sudo` is required) but GNOME D-Bus GUI tool [d-feet](https://wiki.gnome.org/Apps/DFeet) also doesn't send the flag which means that requiring the flag in USBGuard would break use from d-feet, as of today. I have opened a ticket for clarification with d-feet upstream at https://gitlab.gnome.org/GNOME/d-feet/-/issues/26 now.

I'm looking forward to your feedback :beers:

2022-09-27 10:19 UTC, muelli commented
> GUI tool [d-feet](https://wiki.gnome.org/Apps/DFeet) also doesn't send the flag which means that requiring the flag in USBGuard would break use from d-feet, as of today.

That's a problem of the tool, i.e. d-feet.
The correct behaviour is to check whether interactive authorisation was allowed by the caller. If the caller doesn't want popups to be spawned, then it'd be nice if usbguard respected that request.
Whether d-feet is capable of creating such a request is not relevant for encoding the correct behaviour.

2022-10-24 08:26 UTC, Cropi commented
Hello @muelli , may I ask you to bump the dependency for gio-2.0 >=2.26 as @hartwork suggested?

2022-10-24 12:14 UTC, hartwork commented
@Cropi @muelli >=2.**4**6 please, see https://libsoup.org/gio/GDBusMessage.html#GDBusMessageFlags

2022-10-24 20:36 UTC, muelli commented
> Hello @muelli , may I ask you to bump the dependency for gio-2.0 >=2.26 as @hartwork suggested?

I think I tried but couldn't add this new dependency to configure.ac since my autotools-fu is not very good. But I can try again.

2022-10-24 22:31 UTC, hartwork commented
@muelli I believe we need something like this:

```diff
   #
   # Check for required D-Bus modules
   #
-  PKG_CHECK_MODULES([dbus], [dbus-1 gio-2.0 polkit-gobject-1],
+  PKG_CHECK_MODULES([dbus], [dbus-1 gio-2.0 >= 2.46 polkit-gobject-1],
   [AC_DEFINE([HAVE_DBUS], [1], [Required GDBus API available])
   dbus_summary="system-wide; $dbus_CFLAGS $dbus_LIBS"],
   [AC_MSG_FAILURE([Required D-Bus modules (dbus-1, gio-2.0, polkit-gobject-1) not found!])]
```

You can try with a version that your system has no way of satisfying — e.g. `100.0` — to see if things fail as expected. Script `./autogen.sh` can be used to regenerated `configure` from `configure.ac` sources.

2022-11-05 21:01 UTC, muelli commented
I've added the check now.
It bails out when I put a fantasy value for the version, so I believe it's working as intended.

I haven't tested these changes, though.

2022-11-07 15:36 UTC, muelli commented
okay, I've managed to test the change.
The flag is correctly received by USBGuard.
For some reason I don't yet understand, it allows me everything all the time. So there might be glitch in the code, but given that it looks so innocent, I guess it's my system's configuration.

2022-11-16 07:55 UTC, Cropi approved these changes

2022-11-21 08:43 UTC, merged